package knurl.domain.models

import java.time.Instant
import kotlin.uuid.Uuid

data class AuthConfig(
    val instagramAccountId: String,
    val accessToken: String,
    val expiresAt: Instant,
    val updatedAt: Instant,
)

/**
 * `id` is a surrogate primary key generated by Postgres (native `uuidv7()`, see the V1
 * migration) - it is never chosen by application code, only read back from the database.
 * `instagramMediaId` is the natural key from Meta's Graph API and is what ingestion upserts
 * and S3 object keys are keyed by, since it is known before a row exists.
 */
data class InstagramPost(
    val id: Uuid,
    val instagramAccountId: String,
    val instagramMediaId: String,
    val mediaType: String,
    val caption: String?,
    val permalink: String,
    val timestamp: Instant,
    val mediaItems: List<PostMediaItem>,
    val isPinned: Boolean = false,
    val createdAt: Instant = Instant.now(),
)

/**
 * A curated, named collection of an account's catalog items. [id] is the immutable identity public
 * URLs are built from; [name] is a label an admin can change at any time without breaking a link.
 *
 * [itemCount] is how many items an admin has put in the gallery; [publishedCount] is how many of
 * those actually have downloaded media and therefore appear in it. The gap between them is
 * "added, but ingestion hasn't fetched it yet" - which is precisely the question an admin asks
 * after curating, and otherwise looks like items silently going missing.
 */
data class Gallery(
    val id: Uuid,
    val instagramAccountId: String,
    val name: String,
    val itemCount: Int,
    val publishedCount: Int,
    val createdAt: Instant,
    val updatedAt: Instant,
)

/**
 * One post as it appears *in a particular gallery*, with that gallery's own engagement counters.
 *
 * The counters are a wrapper around [post] rather than fields on [InstagramPost] because they are
 * genuinely not properties of the post: the same photo carries independent counts in every gallery
 * holding it. [galleryId] travels with them so a value of this type can never be logged, cached or
 * passed along without saying whose counters these are.
 */
data class GalleryPost(
    val galleryId: Uuid,
    val post: InstagramPost,
    val viewCount: Int,
    val clickCount: Int,
    /** Curator-defined ascending rank in this gallery, or null for timestamp-based placement. */
    val sortOrder: Long?,
)

/** Result of [knurl.domain.repositories.GalleryRepository.updateItems]. */
data class GalleryItemsResult(
    val added: Set<String>,
    val alreadyPresent: Set<String>,
    val removed: Set<String>,
    val sortOrdersUpdated: Set<String>,
    val notFound: Set<String>,
)

/**
 * Result of [knurl.domain.repositories.GalleryRepository.delete]. [itemsReleased] is how many items
 * lost their last gallery membership and therefore just started a retention countdown - the number
 * an admin deserves to be told, since deleting a gallery is otherwise a silent way to schedule a lot
 * of media for deletion.
 */
data class GalleryDeleteResult(
    val name: String,
    val itemsRemoved: Int,
    val itemsReleased: Int,
)

/**
 * One downloaded image/video belonging to a post, in carousel display order. Most posts have
 * exactly one of these (`position` 0); `CAROUSEL_ALBUM` posts have one per child.
 *
 * [mediaType] (`"IMAGE"`/`"VIDEO"`) is this child's own type as reported by the Graph API -
 * independent of the owning [InstagramPost.mediaType], which for a `CAROUSEL_ALBUM` post says
 * nothing about any individual child. [videoPath] answers a different question (has a video asset
 * actually been downloaded to S3?), not the media's semantic type - a video whose download hasn't
 * completed yet can have [mediaType] `"VIDEO"` and a null [videoPath].
 */
data class PostMediaItem(
    val id: Uuid,
    val postId: Uuid,
    val position: Int,
    val mediaType: String,
    val smallPath: String,
    val smallFileSizeBytes: Long,
    val smallWidth: Int,
    val smallHeight: Int,
    val largePath: String,
    val largeFileSizeBytes: Long,
    val largeWidth: Int,
    val largeHeight: Int,
    val videoPath: String?,
    val videoFileSizeBytes: Long?,
    val videoWidth: Int?,
    val videoHeight: Int?,
)

/** Input to [InstagramPostRepository.upsert][knurl.domain.repositories.InstagramPostRepository.upsert] for one [PostMediaItem], before it has a surrogate `id`/`postId`. */
data class PostMediaItemUpsert(
    val position: Int,
    val mediaType: String,
    val smallPath: String,
    val smallFileSizeBytes: Long,
    val smallWidth: Int,
    val smallHeight: Int,
    val largePath: String,
    val largeFileSizeBytes: Long,
    val largeWidth: Int,
    val largeHeight: Int,
    val videoPath: String?,
    val videoFileSizeBytes: Long?,
    val videoWidth: Int?,
    val videoHeight: Int?,
)

/**
 * Fields known to the ingestion pipeline before a post exists in the database - i.e. everything
 * except the surrogate `id` and `createdAt`, which Postgres assigns via column defaults on first
 * insert. Used as the input to [InstagramPostRepository.upsert][knurl.domain.repositories.InstagramPostRepository.upsert].
 */
data class InstagramPostUpsert(
    val instagramAccountId: String,
    val instagramMediaId: String,
    val mediaType: String,
    val caption: String?,
    val permalink: String,
    val timestamp: Instant,
    val mediaItems: List<PostMediaItemUpsert>,
)

/**
 * One row per item in the target account's entire Instagram media feed - populated automatically
 * every ingestion cycle regardless of which galleries, if any, hold it. Holds metadata only, plus
 * one cheap [thumbnailPath] (no large/video S3 paths); an actual [InstagramPost] is only created
 * once an admin puts the entry in a gallery.
 *
 * [notDigestibleReason] is null for a normal, downloadable item. A non-null value (e.g.
 * `"copyright"`) means ingestion has determined the underlying media can never be fetched via the
 * Graph API - adding it to a gallery would sit forever without ever producing an [InstagramPost].
 *
 * [thumbnailPath] is null until a thumbnail has been fetched and stored (or the fetch hasn't
 * succeeded yet - retried every sync cycle, no permanent-failure tracking). Not admin-writable;
 * written only by the ingestion pipeline's thumbnail fetch, independent of gallery membership.
 *
 * [deselectedAt] and [purgeRequestedAt] are the deletion clock for the item's *downloaded media*
 * (its [InstagramPost] row and S3 objects) - never for this catalog row itself, which always
 * survives so the item stays browsable and re-addable. [deselectedAt] is stamped when the item
 * leaves its *last* gallery and starts the configured grace period; [purgeRequestedAt] is stamped
 * by the admin purge endpoint and skips that grace period entirely. Both are cleared when the item
 * is added back to any gallery, which is what makes it ineligible for deletion again and restarts
 * the countdown from scratch if it is ever removed once more.
 */
data class CatalogEntry(
    val instagramMediaId: String,
    val instagramAccountId: String,
    val shortcode: String,
    val mediaType: String,
    val caption: String?,
    val permalink: String,
    val timestamp: Instant,
    val notDigestibleReason: String?,
    val thumbnailPath: String?,
    val deselectedAt: Instant?,
    val purgeRequestedAt: Instant?,
    val updatedAt: Instant,
    /**
     * Every gallery this item currently belongs to, possibly none. Populated by a batched follow-up
     * query rather than an aggregate on the catalog row itself, the same way [InstagramPost]
     * gathers its [PostMediaItem]s.
     */
    val galleryIds: List<Uuid> = emptyList(),
    /** Explicit curator ranks keyed by gallery id; absent means timestamp-based placement. */
    val gallerySortOrders: Map<Uuid, Long> = emptyMap(),
)

/**
 * Fields known to the ingestion pipeline before a catalog row exists - everything except
 * `thumbnailPath` (written separately by the thumbnail fetch step, never clobbered by this upsert)
 * and `updatedAt` (left to the column default / `CURRENT_TIMESTAMP` on conflict). Gallery
 * membership lives in its own table and is admin-owned, so a re-sync cannot disturb it at all.
 */
data class CatalogUpsert(
    val instagramMediaId: String,
    val instagramAccountId: String,
    val shortcode: String,
    val mediaType: String,
    val caption: String?,
    val permalink: String,
    val timestamp: Instant,
    val notDigestibleReason: String?,
)

/**
 * Result of [knurl.domain.repositories.CatalogRepository.requestPurge].
 *
 * [accepted] had both a catalog row and an `instagram_posts` row, so media will actually be
 * deleted; [notInGallery] had a catalog row but nothing downloaded, so there was nothing to
 * delete (it was still deselected defensively). Requested shortcodes absent from both were not
 * found for this account. Split this way rather than returned as a status-per-shortcode map so
 * the repository stays free of HTTP-facing vocabulary - the route maps these to its own statuses.
 */
data class PurgeRequestResult(
    val accepted: Set<String>,
    val notDownloaded: Set<String>,
)

data class SyncConfiguration(
    val key: String,
    val value: String,
)

/**
 * One page of rows plus the total number matching the query, for offset pagination.
 *
 * [currentPage] and [totalPages] are 1-based, and [currentPage] is the *effective* page actually
 * fetched - see [of], which clamps the caller's request rather than erroring. Callers rendering an
 * HTTP envelope should report these two fields rather than echoing what the client asked for.
 */
data class Page<T>(
    val items: List<T>,
    val totalRecords: Int,
    val currentPage: Int,
    val totalPages: Int,
) {
    companion object {
        /**
         * Clamps [requestedPage] into `1..totalPages` and invokes [fetch] with the corresponding
         * row offset. Clamping (rather than rejecting) matches the silent `coerceIn` convention
         * the gallery's `limit` parameter already uses.
         *
         * [totalPages] is at least 1 even for an empty result set, so a caller always has a
         * coherent page to link to. When nothing matched, [fetch] is skipped entirely - there is
         * no point issuing a row query that cannot return anything.
         */
        fun <T> of(
            totalRecords: Int,
            pageSize: Int,
            requestedPage: Int,
            fetch: (offset: Int) -> List<T>,
        ): Page<T> {
            require(pageSize > 0) { "pageSize must be positive, was $pageSize" }
            val totalPages = if (totalRecords <= 0) 1 else (totalRecords + pageSize - 1) / pageSize
            val currentPage = requestedPage.coerceIn(1, totalPages)
            val items = if (totalRecords <= 0) emptyList() else fetch((currentPage - 1) * pageSize)
            return Page(
                items = items,
                totalRecords = maxOf(totalRecords, 0),
                currentPage = currentPage,
                totalPages = totalPages,
            )
        }
    }
}

/**
 * Server-side filters for [knurl.domain.repositories.CatalogRepository.findPage]. Grouped into one
 * type rather than passed as loose parameters so the row query and its matching `COUNT(*)` cannot
 * drift apart - a paginated response whose total disagrees with its rows is worse than no total.
 *
 * An empty [mediaTypes] means "no media-type restriction", not "match nothing".
 */
data class CatalogFilter(
    /** Restrict to items belonging to this specific gallery. */
    val galleryId: Uuid? = null,
    /** Restrict to items belonging to at least one gallery (`true`) or to none at all (`false`). */
    val inAnyGallery: Boolean? = null,
    val mediaTypes: Set<String> = emptySet(),
    val includeNotDigestible: Boolean = true,
)

enum class SortOrder {
    CURATED,
    RECENT,
    VIEWS,
    ;

    companion object {
        fun fromQueryParam(raw: String?): SortOrder =
            when (raw?.lowercase()) {
                null, "curated" -> CURATED
                "recent" -> RECENT
                "views" -> VIEWS
                else -> throw IllegalArgumentException("Unsupported sort value: $raw")
            }
    }
}

data class EvictionCandidate(
    val id: Uuid,
    val mediaPaths: List<String>,
)
