package knurl.domain.models

import java.time.Instant
import kotlin.uuid.Uuid

data class AuthConfig(
    val instagramAccountId: String,
    val accessToken: String,
    val expiresAt: Instant,
    val updatedAt: Instant,
)

/**
 * `id` is a surrogate primary key generated by Postgres (native `uuidv7()`, see the V1
 * migration) - it is never chosen by application code, only read back from the database.
 * `instagramMediaId` is the natural key from Meta's Graph API and is what ingestion upserts
 * and S3 object keys are keyed by, since it is known before a row exists.
 */
data class InstagramPost(
    val id: Uuid,
    val instagramAccountId: String,
    val instagramMediaId: String,
    val mediaType: String,
    val caption: String?,
    val permalink: String,
    val timestamp: Instant,
    val mediaItems: List<PostMediaItem>,
    val viewCount: Int = 0,
    val clickCount: Int = 0,
    val isPinned: Boolean = false,
    val createdAt: Instant = Instant.now(),
)

/**
 * One downloaded image/video belonging to a post, in carousel display order. Most posts have
 * exactly one of these (`position` 0); `CAROUSEL_ALBUM` posts have one per child. A null
 * `videoPath` means this item is an image - the same convention [InstagramPost] used before this
 * became a one-to-many relationship.
 */
data class PostMediaItem(
    val id: Uuid,
    val postId: Uuid,
    val position: Int,
    val smallPath: String,
    val largePath: String,
    val videoPath: String?,
)

/** Input to [InstagramPostRepository.upsert][knurl.domain.repositories.InstagramPostRepository.upsert] for one [PostMediaItem], before it has a surrogate `id`/`postId`. */
data class PostMediaItemUpsert(
    val position: Int,
    val smallPath: String,
    val largePath: String,
    val videoPath: String?,
)

/**
 * Fields known to the ingestion pipeline before a post exists in the database - i.e. everything
 * except the surrogate `id` and `createdAt`, which Postgres assigns via column defaults on first
 * insert. Used as the input to [InstagramPostRepository.upsert][knurl.domain.repositories.InstagramPostRepository.upsert].
 */
data class InstagramPostUpsert(
    val instagramAccountId: String,
    val instagramMediaId: String,
    val mediaType: String,
    val caption: String?,
    val permalink: String,
    val timestamp: Instant,
    val mediaItems: List<PostMediaItemUpsert>,
)

/**
 * One row per item in the target account's entire Instagram media feed - populated automatically
 * every ingestion cycle regardless of [selected] state. Holds metadata only, plus one cheap
 * [thumbnailPath] (no large/video S3 paths); an actual [InstagramPost] is only created once a
 * catalog entry is marked `selected` by an admin.
 *
 * [notDigestibleReason] is null for a normal, downloadable item. A non-null value (e.g.
 * `"copyright"`) means ingestion has determined the underlying media can never be fetched via the
 * Graph API - selecting it would sit forever without ever producing an [InstagramPost].
 *
 * [thumbnailPath] is null until a thumbnail has been fetched and stored (or the fetch hasn't
 * succeeded yet - retried every sync cycle, no permanent-failure tracking). Not admin-writable;
 * written only by the ingestion pipeline's thumbnail fetch, independent of [selected].
 */
data class CatalogEntry(
    val instagramMediaId: String,
    val instagramAccountId: String,
    val shortcode: String,
    val mediaType: String,
    val caption: String?,
    val permalink: String,
    val timestamp: Instant,
    val selected: Boolean,
    val notDigestibleReason: String?,
    val thumbnailPath: String?,
    val updatedAt: Instant,
)

/**
 * Fields known to the ingestion pipeline before a catalog row exists - everything except
 * `selected` (always defaults to/preserves its prior value; only an admin API call changes it),
 * `thumbnailPath` (written separately by the thumbnail fetch step, never clobbered by this
 * upsert - same reasoning as `selected`), and `updatedAt` (left to the column default /
 * `CURRENT_TIMESTAMP` on conflict).
 */
data class CatalogUpsert(
    val instagramMediaId: String,
    val instagramAccountId: String,
    val shortcode: String,
    val mediaType: String,
    val caption: String?,
    val permalink: String,
    val timestamp: Instant,
    val notDigestibleReason: String?,
)

/** Result of [knurl.domain.repositories.CatalogRepository.updateSelection]. */
data class CatalogSelectionResult(
    val selectedShortcodes: Set<String>,
    val deselectedShortcodes: Set<String>,
)

data class SyncConfiguration(
    val key: String,
    val value: String,
)

/**
 * One page of rows plus the total number matching the query, for offset pagination.
 *
 * [currentPage] and [totalPages] are 1-based, and [currentPage] is the *effective* page actually
 * fetched - see [of], which clamps the caller's request rather than erroring. Callers rendering an
 * HTTP envelope should report these two fields rather than echoing what the client asked for.
 */
data class Page<T>(
    val items: List<T>,
    val totalRecords: Int,
    val currentPage: Int,
    val totalPages: Int,
) {
    companion object {
        /**
         * Clamps [requestedPage] into `1..totalPages` and invokes [fetch] with the corresponding
         * row offset. Clamping (rather than rejecting) matches the silent `coerceIn` convention
         * the gallery's `limit` parameter already uses.
         *
         * [totalPages] is at least 1 even for an empty result set, so a caller always has a
         * coherent page to link to. When nothing matched, [fetch] is skipped entirely - there is
         * no point issuing a row query that cannot return anything.
         */
        fun <T> of(
            totalRecords: Int,
            pageSize: Int,
            requestedPage: Int,
            fetch: (offset: Int) -> List<T>,
        ): Page<T> {
            require(pageSize > 0) { "pageSize must be positive, was $pageSize" }
            val totalPages = if (totalRecords <= 0) 1 else (totalRecords + pageSize - 1) / pageSize
            val currentPage = requestedPage.coerceIn(1, totalPages)
            val items = if (totalRecords <= 0) emptyList() else fetch((currentPage - 1) * pageSize)
            return Page(
                items = items,
                totalRecords = maxOf(totalRecords, 0),
                currentPage = currentPage,
                totalPages = totalPages,
            )
        }
    }
}

/**
 * Server-side filters for [knurl.domain.repositories.CatalogRepository.findPage]. Grouped into one
 * type rather than passed as loose parameters so the row query and its matching `COUNT(*)` cannot
 * drift apart - a paginated response whose total disagrees with its rows is worse than no total.
 *
 * An empty [mediaTypes] means "no media-type restriction", not "match nothing".
 */
data class CatalogFilter(
    val selected: Boolean? = null,
    val mediaTypes: Set<String> = emptySet(),
    val includeNotDigestible: Boolean = true,
)

enum class SortOrder {
    RECENT,
    VIEWS,
    ;

    companion object {
        fun fromQueryParam(raw: String?): SortOrder =
            when (raw?.lowercase()) {
                null, "recent" -> RECENT
                "views" -> VIEWS
                else -> throw IllegalArgumentException("Unsupported sort value: $raw")
            }
    }
}

data class EvictionCandidate(
    val id: Uuid,
    val mediaPaths: List<String>,
)
