-- Requires PostgreSQL 18+ for the native uuidv7() function used below.

-- 0. Multi-tenant Account Registry
-- `instagram_account_id` is the Graph API business account id - public, non-secret information,
-- safe to use as a URL path segment. `admin_token` gates admin access (catalog browse/selection)
-- to this account's own content; it's set/rotated by whichever `ingestion-service` instance owns
-- this account, not by `presentation-service`.
CREATE TABLE instagram_accounts (
    instagram_account_id VARCHAR(100) PRIMARY KEY,
    admin_token TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 1. System Credential Ledger (one row per account)
CREATE TABLE auth_config (
    instagram_account_id VARCHAR(100) PRIMARY KEY REFERENCES instagram_accounts (instagram_account_id),
    access_token TEXT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. Master Media Assets Ledger
-- `id` is a surrogate primary key generated by Postgres 18's native uuidv7() (time-ordered,
-- B-tree-friendly). `instagram_media_id` is the natural key from Meta's Graph API and is the
-- upsert/dedup target during ingestion sync - globally unique platform-wide, not per-account, so
-- it stays a plain UNIQUE column rather than being composite-keyed with instagram_account_id.
CREATE TABLE instagram_posts (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    instagram_account_id VARCHAR(100) NOT NULL REFERENCES instagram_accounts (instagram_account_id),
    instagram_media_id VARCHAR(100) NOT NULL UNIQUE,
    media_type VARCHAR(20) NOT NULL,
    caption TEXT,
    permalink TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,

    -- In-House Analytics Metrics
    view_count INT NOT NULL DEFAULT 0,
    click_count INT NOT NULL DEFAULT 0,

    -- Retention Controls
    is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2b. Per-post Media Items (Local Railway S3 Object Storage Paths)
-- One row per downloaded image/video belonging to a post, ordered by `position`. Most posts have
-- exactly one row (position 0); CAROUSEL_ALBUM posts have one per child, in carousel display
-- order. `media_type` (`IMAGE`/`VIDEO`) is the authoritative per-item type reported by the Graph
-- API for this child - independent of the post's own `instagram_posts.media_type`, which for a
-- CAROUSEL_ALBUM post says nothing about any individual child. `video_path` stays a separate
-- nullable column rather than being inferred from `media_type`: it answers a different question
-- (has a video asset actually been downloaded to S3?), not the media's semantic type.
CREATE TABLE instagram_post_media (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    post_id UUID NOT NULL REFERENCES instagram_posts (id) ON DELETE CASCADE,
    position INT NOT NULL,
    media_type VARCHAR(20) NOT NULL,
    small_path TEXT NOT NULL,
    small_file_size_bytes BIGINT NOT NULL CHECK (small_file_size_bytes >= 0),
    small_width INT NOT NULL CHECK (small_width > 0),
    small_height INT NOT NULL CHECK (small_height > 0),
    large_path TEXT NOT NULL,
    large_file_size_bytes BIGINT NOT NULL CHECK (large_file_size_bytes >= 0),
    large_width INT NOT NULL CHECK (large_width > 0),
    large_height INT NOT NULL CHECK (large_height > 0),
    video_path TEXT,
    video_file_size_bytes BIGINT CHECK (video_file_size_bytes >= 0),
    video_width INT CHECK (video_width > 0),
    video_height INT CHECK (video_height > 0),
    CHECK (
        (video_path IS NULL AND video_file_size_bytes IS NULL AND video_width IS NULL AND video_height IS NULL)
        OR
        (video_path IS NOT NULL AND video_file_size_bytes IS NOT NULL AND video_width IS NOT NULL AND video_height IS NOT NULL)
    ),
    UNIQUE (post_id, position)
);

-- 3. Full-feed Media Catalog (metadata only, plus one cheap thumbnail - no large/video S3 paths,
-- no full download)
-- Populated unconditionally every ingestion cycle for the account's entire media feed. `selected`
-- is the only column an admin API call ever changes; the automatic catalog upsert never touches
-- it, so re-syncing the feed can't clobber a curator's picks.
CREATE TABLE instagram_media_catalog (
    instagram_media_id VARCHAR(100) PRIMARY KEY,
    instagram_account_id VARCHAR(100) NOT NULL REFERENCES instagram_accounts (instagram_account_id),
    shortcode VARCHAR(50) NOT NULL UNIQUE,
    media_type VARCHAR(20) NOT NULL,
    caption TEXT,
    permalink TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    selected BOOLEAN NOT NULL DEFAULT FALSE,
    -- NULL means normal/downloadable. A non-NULL reason code (currently only "copyright") means
    -- ingestion determined the underlying media can never be fetched via the Graph API - e.g.
    -- Instagram permanently omits `media_url` for video/Reels content flagged with copyrighted
    -- audio. Refreshed on every sync, unlike `selected`, since ingestion is its sole source of truth.
    not_digestible_reason VARCHAR(50),
    -- NULL until a thumbnail has been fetched and stored (or the fetch hasn't succeeded yet -
    -- retried every sync cycle, no permanent-failure tracking). Holds the S3 object key, not a
    -- full URL - presentation-service presigns it on read, same convention as
    -- instagram_post_media's paths. Deliberate exception to "no S3 paths" above: one small
    -- thumbnail object per catalog row, fetched regardless of `selected`, so an admin can browse
    -- real images before deciding what's worth a full download.
    thumbnail_path TEXT,
    -- NULL while the item is selected, or was never selected. Stamped when an admin deselects,
    -- which starts the retention grace period: the `instagram_posts` row and its S3 objects survive
    -- until `deselected_at + retention_days` (see sync_configurations below), so a reselect inside
    -- that window costs nothing - the media is still in the bucket and `existingMediaIds` already
    -- covers it, so ingestion skips the download. Cleared back to NULL on reselect, which is what
    -- makes a later deselection start a *fresh* countdown rather than resuming the old one.
    deselected_at TIMESTAMP WITH TIME ZONE,
    -- NULL normally. Stamped by DELETE /api/v1/admin/accounts/{id}/catalog/media to mean "skip the
    -- grace period entirely, delete this item's downloaded media on the next ingestion cycle".
    -- A separate column rather than a backdated `deselected_at` sentinel: a retention date of 1970
    -- is a lie the admin UI would have to render, and arming a purge must not silently depend on
    -- whatever `retention_days` happens to be at the moment of the request. Cleared on reselect.
    purge_requested_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 4. Ingestion & Scope Constraints Key-Value Registry
-- Global, not per-account: every account's retention and sweep behaviour uses the same values,
-- applied independently within each account's own post pool (see idx_posts_account_timestamp).
-- Runtime-tunable without a redeploy, which is the whole point of keeping these here rather than
-- in the Hoplite config - notably `orphan_sweep_dry_run`, which an operator wants to toggle
-- against a live deployment before arming a destructive sweep.
--
--   retention_days              (default 30)    grace period between deselection and deletion
--   orphan_sweep_interval_hours (default 24)    minimum gap between full bucket sweeps
--   orphan_grace_minutes        (default 60)    an object younger than this is never an orphan
--   orphan_sweep_max_deletes    (default 1000)  deletion cap per sweep
--   orphan_sweep_dry_run        (default false) log what would be deleted, delete nothing
--   last_orphan_sweep_at                        epoch seconds; written by the sweep claim, not an
--                                               operator knob (see SyncConfigurationRepository.claimIfElapsed)
--   vanished_media_max_percent  (default 50)    refuse to remove catalog entries Instagram's feed no
--                                               longer returned if they're more than this % of the
--                                               account's catalog (a floor of 5 items always proceeds
--                                               regardless of percentage - see SyncPipeline.shouldSkipVanishedRemoval)
CREATE TABLE sync_configurations (
    key VARCHAR(50) PRIMARY KEY,
    value TEXT NOT NULL
);

-- Create strategic indexes to support fast, low-latency API sorting limits.
--
-- The composite indexes below are account-scoped AND carry the same trailing tiebreaker column
-- used by InstagramPostRepository.findPage / CatalogRepository.findPage's ORDER BY (`id` /
-- `instagram_media_id`). That tiebreaker is a correctness requirement for offset pagination, not
-- just a performance one: `timestamp`/`view_count` alone are not unique, and paging over a
-- partial order lets the same row appear on two pages (or on neither). A composite index's
-- leading column already serves any plain account-only equality lookup (e.g. existingMediaIds,
-- selectedMediaIds, mediaIdsNeedingThumbnail), so no separate single-column account index is kept.
CREATE INDEX idx_posts_account_timestamp ON instagram_posts (instagram_account_id, timestamp DESC, id);
CREATE INDEX idx_posts_account_view_count ON instagram_posts (instagram_account_id, view_count DESC, id);
CREATE INDEX idx_post_media_post_id ON instagram_post_media (post_id);
CREATE INDEX idx_catalog_selected ON instagram_media_catalog (selected);
-- Partial indexes: both columns are NULL for the overwhelming majority of rows (an item is
-- normally either selected or was never selected), so these stay tiny while still letting the
-- retention sweep find the handful of rows on a deletion clock without a full catalog scan.
CREATE INDEX idx_catalog_deselected_at ON instagram_media_catalog (deselected_at) WHERE deselected_at IS NOT NULL;
CREATE INDEX idx_catalog_purge_requested ON instagram_media_catalog (purge_requested_at) WHERE purge_requested_at IS NOT NULL;
CREATE INDEX idx_catalog_account_timestamp ON instagram_media_catalog (instagram_account_id, timestamp DESC, instagram_media_id);
CREATE INDEX idx_catalog_needs_thumbnail ON instagram_media_catalog (instagram_account_id) WHERE thumbnail_path IS NULL;
