-- Requires PostgreSQL 18+ for the native uuidv7() function used below.

-- 0. Multi-tenant Account Registry
-- `instagram_account_id` is the Graph API business account id - public, non-secret information,
-- safe to use as a URL path segment. `admin_token` gates admin access (catalog browse/selection)
-- to this account's own content; it's set/rotated by whichever `ingestion-service` instance owns
-- this account, not by `presentation-service`.
CREATE TABLE instagram_accounts (
    instagram_account_id VARCHAR(100) PRIMARY KEY,
    admin_token TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 1. System Credential Ledger (one row per account)
CREATE TABLE auth_config (
    instagram_account_id VARCHAR(100) PRIMARY KEY REFERENCES instagram_accounts (instagram_account_id),
    access_token TEXT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. Master Media Assets Ledger
-- `id` is a surrogate primary key generated by Postgres 18's native uuidv7() (time-ordered,
-- B-tree-friendly). `instagram_media_id` is the natural key from Meta's Graph API and is the
-- upsert/dedup target during ingestion sync - globally unique platform-wide, not per-account, so
-- it stays a plain UNIQUE column rather than being composite-keyed with instagram_account_id.
CREATE TABLE instagram_posts (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    instagram_account_id VARCHAR(100) NOT NULL REFERENCES instagram_accounts (instagram_account_id),
    instagram_media_id VARCHAR(100) NOT NULL UNIQUE,
    media_type VARCHAR(20) NOT NULL,
    caption TEXT,
    permalink TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,

    -- In-House Analytics Metrics
    view_count INT NOT NULL DEFAULT 0,
    click_count INT NOT NULL DEFAULT 0,

    -- Retention Controls
    is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2b. Per-post Media Items (Local Railway S3 Object Storage Paths)
-- One row per downloaded image/video belonging to a post, ordered by `position`. Most posts have
-- exactly one row (position 0); CAROUSEL_ALBUM posts have one row per child, in carousel display
-- order. A nullable `video_path` alone signals "this item is a video" - the same convention as
-- everywhere else in this schema - so there's no separate media-type column here.
CREATE TABLE instagram_post_media (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    post_id UUID NOT NULL REFERENCES instagram_posts (id) ON DELETE CASCADE,
    position INT NOT NULL,
    small_path TEXT NOT NULL,
    large_path TEXT NOT NULL,
    video_path TEXT,
    UNIQUE (post_id, position)
);

-- 3. Full-feed Media Catalog (metadata only, plus one cheap thumbnail - no large/video S3 paths,
-- no full download)
-- Populated unconditionally every ingestion cycle for the account's entire media feed. `selected`
-- is the only column an admin API call ever changes; the automatic catalog upsert never touches
-- it, so re-syncing the feed can't clobber a curator's picks.
CREATE TABLE instagram_media_catalog (
    instagram_media_id VARCHAR(100) PRIMARY KEY,
    instagram_account_id VARCHAR(100) NOT NULL REFERENCES instagram_accounts (instagram_account_id),
    shortcode VARCHAR(50) NOT NULL UNIQUE,
    media_type VARCHAR(20) NOT NULL,
    caption TEXT,
    permalink TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    selected BOOLEAN NOT NULL DEFAULT FALSE,
    -- NULL means normal/downloadable. A non-NULL reason code (currently only "copyright") means
    -- ingestion determined the underlying media can never be fetched via the Graph API - e.g.
    -- Instagram permanently omits `media_url` for video/Reels content flagged with copyrighted
    -- audio. Refreshed on every sync, unlike `selected`, since ingestion is its sole source of truth.
    not_digestible_reason VARCHAR(50),
    -- NULL until a thumbnail has been fetched and stored (or the fetch hasn't succeeded yet -
    -- retried every sync cycle, no permanent-failure tracking). Holds the S3 object key, not a
    -- full URL - presentation-service presigns it on read, same convention as
    -- instagram_post_media's paths. Deliberate exception to "no S3 paths" above: one small
    -- thumbnail object per catalog row, fetched regardless of `selected`, so an admin can browse
    -- real images before deciding what's worth a full download.
    thumbnail_path TEXT,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 4. Ingestion & Scope Constraints Key-Value Registry
-- Global, not per-account: every account's retention eviction uses the same numeric limits,
-- applied independently within each account's own post pool (see idx_posts_account).
CREATE TABLE sync_configurations (
    key VARCHAR(50) PRIMARY KEY,
    value TEXT NOT NULL
);

-- Create strategic indexes to support fast, low-latency API sorting limits
CREATE INDEX idx_posts_timestamp ON instagram_posts (timestamp DESC);
CREATE INDEX idx_posts_view_count ON instagram_posts (view_count DESC);
CREATE INDEX idx_posts_pinned_status ON instagram_posts (is_pinned);
CREATE INDEX idx_posts_account ON instagram_posts (instagram_account_id);
CREATE INDEX idx_post_media_post_id ON instagram_post_media (post_id);
CREATE INDEX idx_catalog_selected ON instagram_media_catalog (selected);
CREATE INDEX idx_catalog_timestamp ON instagram_media_catalog (timestamp DESC);
CREATE INDEX idx_catalog_account ON instagram_media_catalog (instagram_account_id);
CREATE INDEX idx_catalog_needs_thumbnail ON instagram_media_catalog (instagram_account_id) WHERE thumbnail_path IS NULL;
