-- Requires PostgreSQL 18+ for the native uuidv7() function used below.

-- 0. Multi-tenant Account Registry
-- `instagram_account_id` is the Graph API business account id - public, non-secret information,
-- safe to use as a URL path segment.
--
-- This table holds no credentials. It once carried `admin_token_hash`/`read_token_hash`, written by
-- whichever `ingestion-service` instance owned the account on every startup - which meant an
-- ingestion restart silently overwrote whatever a control plane had provisioned. Presentation
-- tokens now live only in `presentation-service`'s in-memory credential store, sourced per
-- CREDENTIALS_MODE from either its own environment (LOCAL) or a control plane (HTTP), so no
-- deployment has two writers racing over one column. What remains here is identity and work state:
-- the foreign-key anchor that instagram_posts/galleries reference, and the claim timestamps below.
--
-- last_synced_at/sync_claimed_at drive ingestion-service's account-agnostic feed-sync claim: any
-- worker, in any process, claims whichever account is due (last_synced_at NULL or stale) and not
-- currently claimed (sync_claimed_at NULL or stale) via `UPDATE ... FOR UPDATE SKIP LOCKED`, syncs
-- it with no transaction held across the actual work, then clears sync_claimed_at and stamps
-- last_synced_at on success. A crashed or failed attempt simply leaves sync_claimed_at set and
-- stale - the same claim query treats that as abandoned and retakes it once its lease elapses, so
-- there is no separate reaper process and no distinction between "failed" and "crashed".
CREATE TABLE instagram_accounts (
    instagram_account_id VARCHAR(100) PRIMARY KEY,
    last_synced_at TIMESTAMP WITH TIME ZONE,
    sync_claimed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 1. System Credential Ledger (one row per account)
-- `access_token_encrypted` holds the Instagram access token AES-256-GCM-encrypted by
-- CredentialCipher (keyed by CREDENTIAL_ENCRYPTION_KEY, configured independently of the
-- database), not hashed like admin_token_hash above - ingestion-service must recover it in full
-- to replay it to Meta's Graph API on every sync cycle, which a one-way hash can't support.
--
-- instagram_account_id is intentionally NOT a foreign key into instagram_accounts: this table is
-- slated to move into its own database, owned by a future credentials broker service, isolated
-- from the catalog data instagram_accounts anchors. A same-database foreign key can't survive
-- that split, so it's never introduced here. Referential integrity for this relationship is the
-- consuming code's responsibility instead - see AuthConfigStore.delete and its doc comment. A
-- stray auth_config row for a deleted account is inert (nothing will ever request its token
-- again), so this is a deliberate, low-risk trade rather than a stopgap.
CREATE TABLE auth_config (
    instagram_account_id VARCHAR(100) PRIMARY KEY,
    access_token_encrypted TEXT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. Master Media Assets Ledger
-- `id` is a surrogate primary key generated by Postgres 18's native uuidv7() (time-ordered,
-- B-tree-friendly). `instagram_media_id` is the natural key from Meta's Graph API and is the
-- upsert/dedup target during ingestion sync - globally unique platform-wide, not per-account, so
-- it stays a plain UNIQUE column rather than being composite-keyed with instagram_account_id.
CREATE TABLE instagram_posts (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    instagram_account_id VARCHAR(100) NOT NULL REFERENCES instagram_accounts (instagram_account_id),
    instagram_media_id VARCHAR(100) NOT NULL UNIQUE,
    media_type VARCHAR(20) NOT NULL,
    caption TEXT,
    permalink TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,

    -- No analytics counters here: a post can belong to several galleries at once, and engagement is
    -- per-gallery, so `view_count`/`click_count` live on `gallery_items` instead.

    -- Retention Controls
    is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2b. Per-post Media Items (Local Railway S3 Object Storage Paths)
-- One row per downloaded image/video belonging to a post, ordered by `position`. Most posts have
-- exactly one row (position 0); CAROUSEL_ALBUM posts have one per child, in carousel display
-- order. `media_type` (`IMAGE`/`VIDEO`) is the authoritative per-item type reported by the Graph
-- API for this child - independent of the post's own `instagram_posts.media_type`, which for a
-- CAROUSEL_ALBUM post says nothing about any individual child. `video_path` stays a separate
-- nullable column rather than being inferred from `media_type`: it answers a different question
-- (has a video asset actually been downloaded to S3?), not the media's semantic type.
CREATE TABLE instagram_post_media (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    post_id UUID NOT NULL REFERENCES instagram_posts (id) ON DELETE CASCADE,
    position INT NOT NULL,
    media_type VARCHAR(20) NOT NULL,
    small_path TEXT NOT NULL,
    small_file_size_bytes BIGINT NOT NULL CHECK (small_file_size_bytes >= 0),
    small_width INT NOT NULL CHECK (small_width > 0),
    small_height INT NOT NULL CHECK (small_height > 0),
    large_path TEXT NOT NULL,
    large_file_size_bytes BIGINT NOT NULL CHECK (large_file_size_bytes >= 0),
    large_width INT NOT NULL CHECK (large_width > 0),
    large_height INT NOT NULL CHECK (large_height > 0),
    video_path TEXT,
    video_file_size_bytes BIGINT CHECK (video_file_size_bytes >= 0),
    video_width INT CHECK (video_width > 0),
    video_height INT CHECK (video_height > 0),
    CHECK (
        (video_path IS NULL AND video_file_size_bytes IS NULL AND video_width IS NULL AND video_height IS NULL)
        OR
        (video_path IS NOT NULL AND video_file_size_bytes IS NOT NULL AND video_width IS NOT NULL AND video_height IS NOT NULL)
    ),
    UNIQUE (post_id, position)
);

-- 3. Full-feed Media Catalog (metadata only, plus one cheap thumbnail - no large/video S3 paths,
-- no full download)
-- Populated unconditionally every ingestion cycle for the account's entire media feed. Which items
-- an admin has actually curated lives in `gallery_items`, not here, so re-syncing the feed can't
-- clobber a curator's picks - the automatic upsert below touches no column an admin API call owns.
CREATE TABLE instagram_media_catalog (
    instagram_media_id VARCHAR(100) PRIMARY KEY,
    instagram_account_id VARCHAR(100) NOT NULL REFERENCES instagram_accounts (instagram_account_id),
    shortcode VARCHAR(50) NOT NULL UNIQUE,
    media_type VARCHAR(20) NOT NULL,
    caption TEXT,
    permalink TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    -- NULL means normal/downloadable. A non-NULL reason code (currently only "copyright") means
    -- ingestion determined the underlying media can never be fetched via the Graph API - e.g.
    -- Instagram permanently omits `media_url` for video/Reels content flagged with copyrighted
    -- audio. Refreshed on every sync, unlike gallery membership, since ingestion is its sole source of truth.
    not_digestible_reason VARCHAR(50),
    -- NULL until a thumbnail has been fetched and stored (or the fetch hasn't succeeded yet -
    -- retried every sync cycle, no permanent-failure tracking). Holds the S3 object key, not a
    -- full URL - presentation-service presigns it on read, same convention as
    -- instagram_post_media's paths. Deliberate exception to "no S3 paths" above: one small
    -- thumbnail object per catalog row, fetched regardless of gallery membership, so an admin can browse
    -- real images before deciding what's worth a full download.
    thumbnail_path TEXT,
    -- NULL while the item belongs to at least one gallery, or never belonged to any. Stamped when
    -- it leaves its *last* gallery, which starts the retention grace period: the `instagram_posts`
    -- row and its S3 objects survive until `deselected_at + retention_days` (see
    -- sync_configurations below), so re-adding it to any gallery inside that window costs nothing -
    -- the media is still in the bucket and `existingMediaIds` already covers it, so ingestion skips
    -- the download. Cleared back to NULL on re-add, which is what makes a later removal start a
    -- *fresh* countdown rather than resuming the old one.
    --
    -- This column is a denormalisation of "when did membership last hit zero", maintained by the
    -- four paths that can change membership (add, remove, gallery delete, purge). Retention does not
    -- trust it blindly: see the COALESCE onto `instagram_posts.created_at` in findEvictionCandidates,
    -- which guarantees an item in no gallery is eventually reaped even if a stamp were ever missed.
    deselected_at TIMESTAMP WITH TIME ZONE,
    -- NULL normally. Stamped by DELETE /api/v1/admin/accounts/{id}/catalog/media to mean "skip the
    -- grace period entirely, delete this item's downloaded media on the next ingestion cycle".
    -- A separate column rather than a backdated `deselected_at` sentinel: a retention date of 1970
    -- is a lie the admin UI would have to render, and arming a purge must not silently depend on
    -- whatever `retention_days` happens to be at the moment of the request. Cleared when the item is
    -- added back to any gallery.
    purge_requested_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3a. Pending Downloads Queue
-- Durable work queue for "this catalog item is selected into a gallery and has no downloaded
-- media yet" - the account-agnostic replacement for ingestion-service downloading inline during
-- its feed-sync pass. Carries identity only, no payload: Instagram's media_url/thumbnail_url are
-- short-lived CDN links that are never persisted anywhere in this schema, so a queued item's fresh
-- URLs are re-fetched from the Graph API at claim time, immediately before downloading, precisely
-- so an arbitrarily old backlog entry never causes a stale-URL failure.
--
-- status/claimed_at is the same claim-and-release, lease-based pattern as instagram_accounts'
-- sync_claimed_at above, made an explicit three-value status here because a download is a
-- one-shot job that reaches a genuine terminal state (COMPLETE), unlike an account, which cycles
-- back to due again. claimed_at is only meaningful while status = 'CLAIMED'; a failed attempt
-- leaves both status and claimed_at untouched, and the claim query below treats a CLAIMED row
-- whose claimed_at has passed the lease duration as abandoned and reclaims it - indistinguishably
-- whether the previous worker failed cleanly or crashed outright.
--
-- Composite (instagram_account_id, instagram_media_id) primary key rather than a surrogate id:
-- nothing else references this row by id, the natural key is already exactly what the enqueue-time
-- ON CONFLICT DO NOTHING dedup and the claim/complete statements need, and it keeps "mark complete
-- on success, leave alone on failure" a one-statement operation with no id indirection.
CREATE TABLE pending_downloads (
    instagram_account_id VARCHAR(100) NOT NULL REFERENCES instagram_accounts (instagram_account_id),
    instagram_media_id VARCHAR(100) NOT NULL
        REFERENCES instagram_media_catalog (instagram_media_id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL DEFAULT 'UNCLAIMED'
        CHECK (status IN ('UNCLAIMED', 'CLAIMED', 'COMPLETE')),
    enqueued_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    claimed_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (instagram_account_id, instagram_media_id)
);

-- 3b. Galleries
-- An account curates any number of named galleries over the same catalog, so one piece of content
-- can appear in several at once. `id` is the immutable identity - it is what public URLs are built
-- from - while `name` is a human-facing label an admin is free to change at any time without
-- breaking a single link.
CREATE TABLE galleries (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    instagram_account_id VARCHAR(100) NOT NULL REFERENCES instagram_accounts (instagram_account_id),
    name TEXT NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 100),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- No triggers exist anywhere in this schema, so this is written explicitly by the rename
    -- statement. A column nothing ever writes would be worse than no column at all.
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3c. Gallery Membership
-- Replaces the old `instagram_media_catalog.selected` boolean. Membership in *any* gallery now does
-- every job that flag did: it gates the download in `SyncPipeline`, protects a post from the
-- retention sweep, and - when the last one ends - starts the deletion clock.
--
-- Both ON DELETE CASCADEs carry weight. The catalog one is what makes "media vanished from
-- Instagram => gone from every gallery containing it" a structural property of the schema rather
-- than something `SyncPipeline.removeVanishedMedia` has to remember to do.
--
-- The counters live here, not on `instagram_posts`, because they are genuinely per-gallery: the
-- same photo's popularity in a "Travel" gallery says nothing about it in "Portfolio", and each
-- gallery's `sort=views` should reflect its own audience. The corollary is that removing an item
-- from a gallery discards that gallery's counters for it; re-adding starts from zero.
CREATE TABLE gallery_items (
    gallery_id UUID NOT NULL REFERENCES galleries (id) ON DELETE CASCADE,
    instagram_media_id VARCHAR(100) NOT NULL
        REFERENCES instagram_media_catalog (instagram_media_id) ON DELETE CASCADE,
    view_count INT NOT NULL DEFAULT 0,
    click_count INT NOT NULL DEFAULT 0,
    added_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (gallery_id, instagram_media_id)
);

-- 4. Ingestion & Scope Constraints Key-Value Registry
-- Global, not per-account: every account's retention and sweep behaviour uses the same values,
-- applied independently within each account's own post pool (see idx_posts_account_timestamp).
-- Runtime-tunable without a redeploy, which is the whole point of keeping these here rather than
-- in the Hoplite config - notably `orphan_sweep_dry_run`, which an operator wants to toggle
-- against a live deployment before arming a destructive sweep.
--
--   retention_days              (default 30)    grace period between deselection and deletion
--   orphan_sweep_interval_hours (default 24)    minimum gap between full bucket sweeps
--   orphan_grace_minutes        (default 60)    an object younger than this is never an orphan
--   orphan_sweep_max_deletes    (default 1000)  deletion cap per sweep
--   orphan_sweep_dry_run        (default false) log what would be deleted, delete nothing
--   last_orphan_sweep_at                        epoch seconds; written by the sweep claim, not an
--                                               operator knob (see SyncConfigurationRepository.claimIfElapsed)
--   vanished_media_max_percent  (default 50)    refuse to remove catalog entries Instagram's feed no
--                                               longer returned if they're more than this % of the
--                                               account's catalog (a floor of 5 items always proceeds
--                                               regardless of percentage - see SyncPipeline.shouldSkipVanishedRemoval)
CREATE TABLE sync_configurations (
    key VARCHAR(50) PRIMARY KEY,
    value TEXT NOT NULL
);

-- Create strategic indexes to support fast, low-latency API sorting limits.
--
-- Every paginated index below carries the same trailing tiebreaker column used by its query's
-- ORDER BY. That tiebreaker is a correctness requirement for offset pagination, not just a
-- performance one: `timestamp`/`view_count` alone are not unique, and paging over a partial order
-- lets the same row appear on two pages (or on neither).
--
-- `idx_posts_account_timestamp`'s `timestamp DESC, id` tail no longer drives a page - gallery
-- content is paged off `gallery_items` now - but the index stays for its leading column, which
-- serves every account-only equality lookup over posts (existingMediaIds, findEvictionCandidates,
-- countOrphanedPosts, deleteVanished).
CREATE INDEX idx_posts_account_timestamp ON instagram_posts (instagram_account_id, timestamp DESC, id);
CREATE INDEX idx_post_media_post_id ON instagram_post_media (post_id);

-- Names are the admin's handle on a gallery, so two that differ only by case or padding would be
-- indistinguishable in a picker. This has to be a CREATE UNIQUE INDEX rather than a table-level
-- UNIQUE constraint: Postgres accepts only bare column names in the latter, so `UNIQUE
-- (instagram_account_id, lower(btrim(name)))` is a syntax error. Its leading column doubles as the
-- account scan for GET /api/v1/accounts/{accountId}/galleries.
CREATE UNIQUE INDEX uq_galleries_account_name ON galleries (instagram_account_id, lower(btrim(name)));

-- Postgres does not auto-index the referencing side of a foreign key, and this particular side is
-- probed constantly: the "is this post in any gallery?" semi-join (once per eviction candidate per
-- cycle, and again as the download gate), the "are there memberships left?" check on every removal,
-- the admin catalog's gallery filters, and the ON DELETE CASCADE that deleteVanished fires once per
-- deleted catalog row. Without this index all four fall back to sequential scans of gallery_items.
CREATE INDEX idx_gallery_items_media ON gallery_items (instagram_media_id);

-- Serves `ORDER BY gi.view_count DESC, gi.instagram_media_id` for a gallery's sort=views. The
-- tiebreaker is the media id rather than the post id precisely so this index can serve the whole
-- ordering: within a fixed gallery_id it is unique (it is the other half of the primary key), so it
-- is a valid total order. The PK itself covers the gallery content scan and item counts.
CREATE INDEX idx_gallery_items_views ON gallery_items (gallery_id, view_count DESC, instagram_media_id);

-- Partial indexes: both columns are NULL for the overwhelming majority of rows (an item normally
-- either belongs to a gallery or never did), so these stay tiny while still letting the retention
-- sweep find the handful of rows on a deletion clock without a full catalog scan.
CREATE INDEX idx_catalog_deselected_at ON instagram_media_catalog (deselected_at) WHERE deselected_at IS NOT NULL;
CREATE INDEX idx_catalog_purge_requested ON instagram_media_catalog (purge_requested_at) WHERE purge_requested_at IS NOT NULL;
CREATE INDEX idx_catalog_account_timestamp ON instagram_media_catalog (instagram_account_id, timestamp DESC, instagram_media_id);
CREATE INDEX idx_catalog_needs_thumbnail ON instagram_media_catalog (instagram_account_id) WHERE thumbnail_path IS NULL;

-- Serves the download claim's "unclaimed or stale-claimed, oldest first" scan without a full-table
-- sort; status is low-cardinality but still worth leading the index since the claim query always
-- filters on it first.
CREATE INDEX idx_pending_downloads_claimable ON pending_downloads (status, enqueued_at);

-- Serves the completed-download cleanup sweep's "old COMPLETE rows" scan.
CREATE INDEX idx_pending_downloads_completed_at ON pending_downloads (completed_at) WHERE status = 'COMPLETE';

-- Serves the feed-sync claim's "which accounts are due" scan, including NULL-first ordering for
-- never-synced accounts.
CREATE INDEX idx_accounts_last_synced_at ON instagram_accounts (last_synced_at);
